# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08dc3daf401c006280a0401db8ae5df9002c39524262c9ee27922932754938a8f797ff1cb0356c449becdeecffd6a43654db69cacf6a8455dfbfa5d5e3a06f05

test:
  secret_key_base: ad8c28f91e3e30d4f898bbefce9d25ff2e48832392b4cb323af32bbb5444a8be13d2f6b1e8ab08a0b10379752a7c0d7e45bf59ceef48bbc93bb6d395e7093b8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
